object Versions {
    const val KOTLIN = "1.9.0"
    const val LIFECYCLE_RUNTIME_KTX = "2.6.1"
    const val ACTIVITY_COMPOSE = "1.7.0"
    const val COMPOSE_BOOM = "2023.03.00"
    const val JUNIT_EXT = "1.1.5"
    const val JUNIT = "4.13.2"
    const val ESPRESSO_CORE = "3.5.1"
    const val COMPOSE_COMPILER = "1.4.3"
    const val VIEW_MODEL = "2.6.1"
    const val TIMBER = "5.0.1"
    const val ROOM = "2.3.0"
    const val RETROFIT = "2.9.0"
    const val OKHTTP = "4.9.1"
    const val KOIN = "3.4.0"
}